// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// allRcpp
bool allRcpp(LogicalVector x);
RcppExport SEXP cppStarter_allRcpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< LogicalVector >::type x(xSEXP);
    __result = Rcpp::wrap(allRcpp(x));
    return __result;
END_RCPP
}
// cumprodRcpp
NumericVector cumprodRcpp(NumericVector x);
RcppExport SEXP cppStarter_cumprodRcpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    __result = Rcpp::wrap(cumprodRcpp(x));
    return __result;
END_RCPP
}
// cumminRcpp
NumericVector cumminRcpp(NumericVector x);
RcppExport SEXP cppStarter_cumminRcpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    __result = Rcpp::wrap(cumminRcpp(x));
    return __result;
END_RCPP
}
// cummaxRcpp
NumericVector cummaxRcpp(NumericVector x);
RcppExport SEXP cppStarter_cummaxRcpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    __result = Rcpp::wrap(cummaxRcpp(x));
    return __result;
END_RCPP
}
// diffRcpp
NumericVector diffRcpp(NumericVector x, int lag);
RcppExport SEXP cppStarter_diffRcpp(SEXP xSEXP, SEXP lagSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    __result = Rcpp::wrap(diffRcpp(x, lag));
    return __result;
END_RCPP
}
// varRcpp
double varRcpp(NumericVector x);
RcppExport SEXP cppStarter_varRcpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    __result = Rcpp::wrap(varRcpp(x));
    return __result;
END_RCPP
}
// rangeRcpp
NumericVector rangeRcpp(NumericVector x, bool na_rm);
RcppExport SEXP cppStarter_rangeRcpp(SEXP xSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    __result = Rcpp::wrap(rangeRcpp(x, na_rm));
    return __result;
END_RCPP
}
// minRcpp
double minRcpp(NumericVector x, bool na_rm);
RcppExport SEXP cppStarter_minRcpp(SEXP xSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    __result = Rcpp::wrap(minRcpp(x, na_rm));
    return __result;
END_RCPP
}
// maxRcpp
double maxRcpp(NumericVector x, bool na_rm);
RcppExport SEXP cppStarter_maxRcpp(SEXP xSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    __result = Rcpp::wrap(maxRcpp(x, na_rm));
    return __result;
END_RCPP
}
// maxRcpp2
double maxRcpp2(NumericVector x, bool na_rm);
RcppExport SEXP cppStarter_maxRcpp2(SEXP xSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    __result = Rcpp::wrap(maxRcpp2(x, na_rm));
    return __result;
END_RCPP
}
