# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' allRcpp
#' @description c++ version of base all(). Missing values not accepted.
#' @param x a logical vector
allRcpp <- function(x) {
    .Call('cppStarter_allRcpp', PACKAGE = 'cppStarter', x)
}

#' cumprodRcpp
#' @description c++ version of base cumprod(). Missing values not accepted.
#' @param x a numeric vector
cumprodRcpp <- function(x) {
    .Call('cppStarter_cumprodRcpp', PACKAGE = 'cppStarter', x)
}

#' cumminRcpp
#' @description c++ version of base cummin(). Missing values not accepted.
#' @param x a numeric vector
cumminRcpp <- function(x) {
    .Call('cppStarter_cumminRcpp', PACKAGE = 'cppStarter', x)
}

#' cummaxRcpp
#' @description c++ version of base cummax(). Missing values not accepted.
#' @param x a numeric vector
cummaxRcpp <- function(x) {
    .Call('cppStarter_cummaxRcpp', PACKAGE = 'cppStarter', x)
}

#' diffRcpp
#' @description c++ version of base diff(). Missing values not accepted.
#' @param x a numeric vector
#' @param lag the specified lag
diffRcpp <- function(x, lag = 1L) {
    .Call('cppStarter_diffRcpp', PACKAGE = 'cppStarter', x, lag)
}

#' varRcpp
#' @description c++ version of base var(). Uses a 'two-pass' approach
#' @param x a numeric vector
varRcpp <- function(x) {
    .Call('cppStarter_varRcpp', PACKAGE = 'cppStarter', x)
}

#' rangeRcpp
#' @description c++ version of base range(), can deal with na's
#' @param x a numeric vector
#' @param na_rm boolean, should NA's be considered?
rangeRcpp <- function(x, na_rm = FALSE) {
    .Call('cppStarter_rangeRcpp', PACKAGE = 'cppStarter', x, na_rm)
}

#' minRcpp
#' @description c++ version of base min(). can deal with missing values
#' @param x a numeric vector
#' @param na_rm boolean, should NA's be considered?
minRcpp <- function(x, na_rm = FALSE) {
    .Call('cppStarter_minRcpp', PACKAGE = 'cppStarter', x, na_rm)
}

#' maxRcpp
#' @description c++ version of base max(). can deal with missing values
#' @param x a numeric vector
#' @param na_rm boolean, should NA's be considered?
maxRcpp <- function(x, na_rm = FALSE) {
    .Call('cppStarter_maxRcpp', PACKAGE = 'cppStarter', x, na_rm)
}

#' maxRcpp2
#' @description c++ version of base max(). Different implementation.
#'   can deal with missing values. Its not as fast as maxRcpp()
#' @param x a numeric vector
#' @param na_rm boolean, should NA's be considered?
maxRcpp2 <- function(x, na_rm = FALSE) {
    .Call('cppStarter_maxRcpp2', PACKAGE = 'cppStarter', x, na_rm)
}

